import { ArrowDown, ArrowRight, BriefcaseBusiness, Code2, GraduationCap, Layers3 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { SetupNotice } from '../components/SetupNotice'
import { useEffect, useState } from 'react'
import { portfolioService } from '../services/portfolio-service'
import type { Experience, Profile, Project, Service, Skill } from '../types/portfolio'

const skillDefaults = ['React', 'TypeScript', 'PHP', 'Node.js', 'Supabase', 'Flutter', 'MySQL', 'REST APIs']
export default function HomePage() { const [profile, setProfile] = useState<Profile | null>(null); const [projects, setProjects] = useState<Project[]>([]); const [skills, setSkills] = useState<Skill[]>([]); const [experience, setExperience] = useState<Experience[]>([]); const [services, setServices] = useState<Service[]>([]); useEffect(() => { void Promise.all([portfolioService.profile(), portfolioService.projects(), portfolioService.skills(), portfolioService.experiences(), portfolioService.services()]).then(([p, pr, s, e, sv]) => {setProfile(p);setProjects(pr);setSkills(s);setExperience(e);setServices(sv)}).catch(console.error) }, []); const name = profile?.full_name || 'Your Name'; return <>
<section className="hero"><div className="hero-grid"><p className="eyebrow">FULL-STACK DEVELOPER · IT PROFESSIONAL</p><h1>Building modern digital solutions for <em>businesses, education, and events.</em></h1><p className="lede">{profile?.biography || 'An experienced IT professional and full-stack developer specializing in web applications, learning management systems, business automation, mobile applications, and custom software solutions.'}</p><div className="actions"><Link className="button primary" to="/projects">View My Projects <ArrowRight size={17}/></Link><Link className="button secondary" to="/contact">Contact Me</Link></div><a className="scroll" href="#about">Explore <ArrowDown size={15}/></a></div><div className="code-card" aria-hidden="true"><span>01 / digital craft</span><pre>{`const impact = await build({\n  strategy: 'human-first',\n  quality: 'production-ready'\n})`}</pre><div><Code2/><b>Systems that work beautifully.</b></div></div></section>
<div className="container"><SetupNotice empty={!profile && projects.length === 0}/><section id="about" className="split section"><div><p className="eyebrow">ABOUT {name.toUpperCase()}</p><h2>Technology with purpose, delivered with clarity.</h2></div><div><p>{profile?.biography || 'Add your professional story in the Admin area. This space is designed to describe your experience leading projects, building systems, and delivering practical outcomes.'}</p>{profile?.resume_url && <a className="text-link" href={profile.resume_url}>Download résumé <ArrowRight size={16}/></a>}</div></section>
<section className="section"><div className="section-title"><div><p className="eyebrow">SELECTED WORK</p><h2>Featured projects</h2></div><Link className="text-link" to="/projects">All projects <ArrowRight size={16}/></Link></div><div className="project-grid">{projects.filter(p => p.is_featured).slice(0, 3).map(project => <ProjectCard key={project.id} project={project}/>) || null}{projects.length === 0 && <Empty label="Featured projects will appear here once published."/>}</div></section>
<section className="section skill-band"><p className="eyebrow">CORE TOOLKIT</p><div className="chips">{(skills.length ? skills.map(s => s.name) : skillDefaults).map(skill => <span key={skill}>{skill}</span>)}</div></section>
<section className="section"><div className="section-title"><div><p className="eyebrow">HOW I CAN HELP</p><h2>Built for the work that matters.</h2></div></div><div className="service-grid">{(services.length ? services : [{id:'1',title:'Custom Web Development',description:'Responsive, reliable websites and web applications built around your goals.'},{id:'2',title:'Business Systems',description:'Practical tools that simplify operations and help teams move faster.'},{id:'3',title:'Learning Platforms',description:'Engaging, structured digital experiences for education and training.'}]).map((s,i) => <article className="service" key={s.id}>{[<Code2/>,<BriefcaseBusiness/>,<GraduationCap/>][i % 3]}<h3>{s.title}</h3><p>{s.description}</p></article>)}</div></section>
{experience.length > 0 && <section className="section"><p className="eyebrow">EXPERIENCE</p><div className="timeline">{experience.map(item => <article key={item.id}><span>{item.start_date} — {item.is_current ? 'Present' : item.end_date}</span><h3>{item.job_title}</h3><p>{item.organization}{item.location ? ` · ${item.location}` : ''}</p></article>)}</div></section>}
<section className="cta section"><Layers3 size={28}/><h2>Have a project in mind?</h2><p>Let’s turn a complex requirement into a clear, dependable digital solution.</p><Link className="button primary" to="/contact">Start a conversation <ArrowRight size={17}/></Link></section></div></> }
export function ProjectCard({ project }: { project: Project }) { return <article className="project-card"><div className="project-image">{project.cover_image_url ? <img src={project.cover_image_url} alt={`${project.title} cover`} loading="lazy"/> : <Layers3 size={42}/>}<span>{project.categories?.[0] || 'Project'}</span></div><div><p className="meta">{project.completion_date?.slice(0,4) || 'Current'} · {project.technologies?.slice(0,2).join(' · ')}</p><h3>{project.title}</h3><p>{project.short_description}</p><Link className="text-link" to={`/projects/${project.slug}`}>View case study <ArrowRight size={16}/></Link></div></article> }
function Empty({ label }: { label: string }) { return <div className="empty"><Layers3 size={24}/><p>{label}</p></div> }
